# Adapted from:
# https://github.com/VaultVulp/gp-docker-action#complete-workflow-example
name: Build and publish

on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish-image:
    if: github.repository == 'mitre/GrowthViz'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Build and publish tagged Docker image
        uses: VaultVulp/gp-docker-action@1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: gv-image
          extract-git-tag: true
