# Adapted from:
# https://github.com/VaultVulp/gp-docker-action#complete-workflow-example
name: Build and publish

on: 
  push:
    branches:
    - "v3-dev"

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0

    - name: Build and publish "head" Docker image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GV_IMAGE_BUILD }} 
        image-name: mitre/growthviz
        image-tag: v3
