# Adapted from:
# https://github.com/VaultVulp/gp-docker-action#complete-workflow-example
name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    if: github.repository == 'mitre/GrowthViz'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Build and publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: gv-image
          image-tag: latest
